### PR TITLE
"Upload to..." menu (Fixes #44)

### LINKED ISSUE #44: Adding context-menu support
I would like to see if it would be possible in the future to add context-menu for uploading PNG, JPG, GIF, JPEG etc.. files to the selected service from files that are already on the computer.

### PR DESCRIPTION
**Pull request by JakeMakesStuff**
This is confirmed working by me.

### CODE REVIEW

**Comment by JakeMakesStuff** [comment]
Fixes #44

**Comment by JakeMakesStuff** [comment]
@SunburntRock89 Seems to. Feel free to point out the sub-standard bits in a review and I'll fix them up. Thanks!

**Comment by JakeMakesStuff** [comment]
@SunburntRock89 I was actually using `for of` a lot more before, but JS was giving me issues about stuff not being iterable.

**Comment by SunburntRock89** [comment]
If it ain't iterable then it ain't an array lol

**Comment by JakeMakesStuff** [comment]
Yeah ik, everything I changed from `of` isn't a array I think.

**Comment by SunburntRock89** [comment]
Hrm, anyhow, assuming you switch out that in statement (can't find any docs of in in that context in node)

**Comment by JakeMakesStuff** [comment]
I mean I'm not sure, it seems to work, but there may be a better way of doing it. I am not the best at Node.

**Comment by SunburntRock89** [comment]
Couldn't say I'd be too sure, if it works then I'll accept changes

**Comment by SunburntRock89** [comment]
Go ahead and merge, I'm on mobile

**Comment by JakeMakesStuff** [comment]
Ok, thanks for reviewing!

**Pull request merged**
