### PR TITLE
Added pays.host support

### PR DESCRIPTION
**Pull request by alexgokhale**

### CODE REVIEW

**Comment by TheOPtimal** [comment]
This is useless, pays.host already provides ShareX SXCUs.

**Comment by alexgokhale** [comment]
Indeed, however a common issue we are experiencing currently is people requesting MagicCap support after not being able to get it to work using a ShareX SXCU. That, combined with the fact that MagicCap doesn't provide a default User Agent is another reason for individual support. elixi.re also offer ShareX SXCUs, however they are an option within MagicCap and there's no harm in having it as an option.

**Comment by SunburntRock89** [comment]
Perhaps it's about time we actually fix some bugs too

**Comment by SynergyBest** [comment]
it's true that for some reason sxcu hasn't worked with pays.host and magiccap

**Comment by SunburntRock89** [comment]
I'd do something if I could. If you're having trouble using this host because of user-agent woes, try creating your own uploader profile of type "Custom" and setting things that way

**Comment by alexgokhale** [comment]
We'd love to, but the fact a node-fetch user agent is then used to verify that the image was properly uploaded causes issues as well, due to the attack methods using the same user agent.

**Comment by SynergyBest** [comment]
image

**Pull request closed without merging**
